types.NewInterfaceType -> types.NewInterface
Changing types.NewInterfaceType to types.NewInterface, because there is no function named NewInterfaceType that causes error when running `go get github.com/99designs/gqlgen/cmd` to the following 
github.com/99designs/gqlgen/codegen/config
# github.com/99designs/gqlgen/codegen/config
../../../99designs/gqlgen/codegen/config/binder.go:86:53: undefined: types.NewInterfaceType
../../../99designs/gqlgen/codegen/config/binder.go:87:21: undefined: types.NewInterfaceType